### ISSUE TITLE
es5.js file not present

### ISSUE THREAD

**Issue by MichaelPaulukonis** [nlp-compromise/nlp-ngram#2]
After a simple `npm i nlp-ngram`, the module cannot be found:

```
> var ng = require('nlp-ngram')
Error: Cannot find module 'nlp-ngram'
    at Function.Module._resolveFilename (module.js:438:15)
```

Perhaps because npm installs main pointing to a non-existent `.es5.js` file:

```
"main": "builds/nlp-ngram.es5.js",
```

It looks like this was fixed in a pull-request on May 20, but the version matches the `0.0.2` version on npm. Although npm reports the last update as 4 months ago....

My suggestion: bump the version, and republish to npm

**Comment by spencermountain** [comment]
thanks Michael, v0.0.3 looks better now
cheers
